# Generated by Django 4.0.4 on 2022-05-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_address', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_name', models.CharField(choices=[('info', 'info'), ('error', 'error'), ('success', 'success'), ('warning', 'warning'), ('question', 'question'), ('back', 'back'), ('arrow-left', 'arrow-left'), ('arrow-down', 'arrow-down'), ('arrow-right', 'arrow-right'), ('arrow-up', 'arrow-up'), ('caret-left', 'caret-left'), ('caret-bottom', 'caret-bottom'), ('caret-top', 'caret-top'), ('caret-right', 'caret-right'), ('d-arrow-left', 'd-arrow-left'), ('d-arrow-right', 'd-arrow-right'), ('minus', 'minus'), ('plus', 'plus'), ('remove', 'remove'), ('circle-plus', 'circle-plus'), ('remove-outline', 'remove-outline'), ('circle-plus-outline', 'circle-plus-outline'), ('close', 'close'), ('check', 'check'), ('circle-close', 'circle-close'), ('circle-check', 'circle-check'), ('circle-close-outline', 'circle-close-outline'), ('circle-check-outline', 'circle-check-outline'), ('zoom-out', 'zoom-out'), ('zoom-in', 'zoom-in'), ('d-caret', 'd-caret'), ('sort', 'sort'), ('sort-down', 'sort-down'), ('sort-up', 'sort-up'), ('tickets', 'tickets'), ('document', 'document'), ('goods', 'goods'), ('sold-out', 'sold-out'), ('news', 'news'), ('message', 'message'), ('date', 'date'), ('printer', 'printer'), ('time', 'time'), ('bell', 'bell'), ('mobile-phone', 'mobile-phone'), ('service', 'service'), ('view', 'view'), ('menu', 'menu'), ('more', 'more'), ('more-outline', 'more-outline'), ('star-on', 'star-on'), ('star-off', 'star-off'), ('location', 'location'), ('phone', 'phone'), ('phone-outline', 'phone-outline'), ('picture', 'picture'), ('picture-outline', 'picture-outline'), ('delete', 'delete'), ('search', 'search'), ('edit', 'edit'), ('edit-outline', 'edit-outline'), ('rank', 'rank'), ('refresh', 'refresh'), ('share', 'share'), ('setting', 'setting'), ('upload', 'upload'), ('upload2', 'upload2'), ('download', 'download'), ('loading', 'loading')], default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.type')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255)),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.page')),
            ],
        ),
    ]
