# Generated by Django 4.0.4 on 2022-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_value',
            field=models.TextField(),
        ),
    ]
