# Generated by Django 4.0.4 on 2022-04-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('pass_word', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
